server:
  port: 886

spring:
  cache:
    cache-names: customers
    caffeine:
      spec: initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats

  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: db_user
    password: password
  jpa:
    hibernate:
      # create, create-drop, update, validate
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true